main: Main.HardcoreGames
name: HardcoreGames
version: 1.0
api-version: 1.16
depend:
  - LuckPerms
  - Citizens
  - Sentinel
  - ProtocolLib
  - SkinsRestorer
commands:
  hardcoregames:
    aliases: hg
  kit:
  help:
  stats: